### ISSUE TITLE
Close the window when the user clicks outside

### ISSUE THREAD

**Issue by MateoPeri** [Bunn/PiStats#12]
All apps on the menu bar (including native ones, like the wifi or bluetooth icon) close whenever you click outside of their area. This should be the case as well, instead of needing to click the icon again to close. The first time I used it I was a little confused as to why the windows wasn't closing whenever I clicked away.

**Comment by TimboSIice** [comment]
I second this.

**Comment by TimboSIice** [comment]
Although I DO see a use for having it stay open sometimes. Sometimes I like to keep it open to look at the stats while I go to different websites. 

Maybe an option to lock it open for some cases? All other times, it hides like the above comment?

**Comment by MateoPeri** [comment]
Yeah, that's what I had in mind. There is already a settings section, so maybe we could have an option to toggle it on or off.

**Comment by Bunn** [comment]
Fixed on version 1.2.0
