### ISSUE TITLE
Cannot seem to connect on local network

### ISSUE THREAD

**Issue by dallasgroot** [Bunn/PiStats#14]
Can't seem to authenticate

![image](https://user-images.githubusercontent.com/7484579/83054463-491bdf00-a007-11ea-8c60-37c22bfeab49.png)

http://192.168.1.64 is pi-hole
https://192.168.1.64 - my ghost blog

**Comment by Bunn** [comment]
solved https://twitter.com/iamgroot11/status/1266032310056415233?s=20
