### ISSUE TITLE
Pi Stats cannot connect to Pi-hole

### ISSUE THREAD

**Issue by miszterx** [Bunn/PiStats#22]
Hi, 
I have the latest 2.2.0 Pi-Stats on MacOs. On the server side I have: Pi-hole v5.1.2  Web Interface v5.1.1  FTL v5.2.

I get the API Token. Took in the necessary field in the Pi-Stats and I just got red icon.
On the server side I have checked the nginx log and I can see:

- - - [18/Aug/2020:14:19:44 +0200] "GET /admin/api.php?auth=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&enable= HTTP/1.1" 400 264 "-" "Pi%20Stats/12 CFNetwork/1128.0.1 Darwin/19.6.0 (x86_64)"
- - - [18/Aug/2020:14:19:46 +0200] "GET /admin/api.php? HTTP/1.1" 400 264 "-" "Pi%20Stats/12 CFNetwork/1128.0.1 Darwin/19.6.0 (x86_64)"

I can see just HTTP code 400. Can you help me with this? 
Thanks!

**Comment by Bunn** [comment]
What happens if you run the same request on cURL?

**Comment by miszterx** [comment]
Hi,
With curl it woks fine:

# curl "https://pihole/admin/api.php?auth=xxxxxxxxxxx&enable="                                                                                                            
{"status":"enabled"}%                                                                                                                                                                                                                       

#curl "https://pihole.xorp.hu/admin/api.php?"                                                                                                                                                                                         
{"domains_being_blocked":337448,"dns_queries_today":10389,"ads_blocked_today":1817,"ads_percentage_today":17.489653,"unique_domains":2254,"queries_forwarded":7110,"queries_cached":1462,"clients_ever_seen":9,"unique_clients":9,"dns_queries_all_types":10389,"reply_NODATA":132,"reply_NXDOMAIN":111,"reply_CNAME":975,"reply_IP":1976,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1598753399,"relative":{"days":2,"hours":7,"minutes":11}}}%    

- - - [01/Sep/2020:11:21:14 +0200] "GET /admin/api.php? HTTP/1.1" 200 490 "-" "curl/7.64.1"

But if the Pi Stats try the same:

- - - [01/Sep/2020:11:21:06 +0200] "GET /admin/api.php? HTTP/1.1" 400 264 "-" "Pi%20Stats/12 CFNetwork/1128.0.1 Darwin/19.6.0 (x86_64)"

I can get 400

Any idea?

**Comment by Bunn** [comment]
@miszterx if you don't mind can you post a screenshot of the Pi Stats preferences window? 
I'm interested in how you configured the URL, is it `https://pihole.xorp.hu`?

**Comment by miszterx** [comment]
Sure. Here it is:

<img width="515" alt="Screenshot 2020-09-01 at 19 46 54" src="https://user-images.githubusercontent.com/56317037/91888080-fdbf3f80-ec8b-11ea-8c31-ee2dcea7a451.png">

I needed to add the port for https. Without the port it wanted to go on port 80 by default. With :443 it goes to the proper HTTPS site definition, but with the result what I reported above.

**Comment by Bunn** [comment]
It seems the issue is when the app tries to access an external URL with HTTPS.
I'm going to add a flag when setting up the pi-hole asking the user if it's http or https, that the app will know what to do.

**Comment by miszterx** [comment]
Perfect! Thanks. I am glad that you could reproduce it.
Looking forward to test the new version.

**Comment by Bunn** [comment]
@miszterx I've added an option for you to configure your pinhole as either HTTP or HTTPS.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/782316/95255386-2dc4aa00-0819-11eb-8791-2435b5f3ef57.png">

I'm attaching the beta version here, if you can give it a try I'd appreciate :)

[PiStatsBeta.zip](https://github.com/Bunn/PiStats/files/5336476/PiStatsBeta.zip)

**Comment by miszterx** [comment]
Works fine! Thanks!

<img width="331" alt="Screenshot 2020-10-08 at 8 12 42" src="https://user-images.githubusercontent.com/56317037/95422230-3a432280-093f-11eb-9118-fc74096682f9.png">
