### ISSUE TITLE
Enable/Disable button does not work

### ISSUE THREAD

**Issue by Lukabratzee** [Bunn/PiStats#25]
I'm able to see accurate stats from my pihole instance but am unable to affect it.

I've attached a screenshot showing my active pihole page and the display from Hole Stats.
When I click the button, it flips and then reverts back to it's original state.

![Screenshot 2020-10-02 at 16 00 39](https://user-images.githubusercontent.com/8959269/94938263-82d68800-04c8-11eb-9a0c-69400b031c03.png)

**Comment by Bunn** [comment]
@Lukabratzee interesting, I see that your Pi-Hole is online but the app says it's offline.
I remember seeing a bug on the Pi-hole API where once you requested it to be offline it wouldn't change the status of the return value but it would change the status on the web API even when the API was returning a different value. Like a buffer to wait for the value to change.

If you close Pi Stats and open again, does it says it's offline?
If it does, please try to open this URL on your browser:

http://YOUR_PI_HOLE_ADDRESS/admin/api.php?summary
And paste the return value here, I'm interested in the `"status":"enabled"` property

**Comment by Bunn** [comment]
Fixed in the latest release

https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529
