### ISSUE TITLE
Consider support for multiple instances of Pi-hole

### ISSUE THREAD

**Issue by jermo5** [Bunn/PiStats#7]
I love the app you’ve built and it would be super useful if you could consider support for more than one pi-hole in your app. 

Myself along with many others run 2+ instances of pi-hole for redundancy purposes and it would be great to be able to use your app to monitor maybe at a minimum 2 instances. This way I could view the stats for all of my pi-hole devices instead of just choosing one. 

Thanks for the great work!

**Comment by Coder84619** [comment]
100% agree! I was all excited to use this new app, but I have redundant Pi-holes. So I won't be using this app until it supports at least dual Pi-Holes.

**Comment by Bunn** [comment]
@Coder84619 @jermo5 support for multiple pi-holes is live on version 2.0.0 :)
